<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ecr.Adapters.Excel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecr.Domain\Ecr.Domain.csproj" />
    <ProjectReference Include="..\Ecr.Application\Ecr.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
  </ItemGroup>

</Project>
