-- src/Ecr.Infrastructure/Persistence/Sql/01-filegroups.sql
ALTER DATABASE [Ecr] ADD FILEGROUP [DATA_HOT];
ALTER DATABASE [Ecr] ADD FILEGROUP [DATA_ARCHIVE];
ALTER DATABASE [Ecr] ADD FILEGROUP [AUDIT];
ALTER DATABASE [Ecr] ADD FILEGROUP [INDEXES];
GO

ALTER DATABASE [Ecr] ADD FILE
  (NAME = N'Ecr_hot',     FILENAME = N'<path>\Ecr_hot.ndf',     SIZE = 4GB, FILEGROWTH = 1GB) TO FILEGROUP [DATA_HOT];
ALTER DATABASE [Ecr] ADD FILE
  (NAME = N'Ecr_archive', FILENAME = N'<path>\Ecr_archive.ndf', SIZE = 4GB, FILEGROWTH = 4GB) TO FILEGROUP [DATA_ARCHIVE];
ALTER DATABASE [Ecr] ADD FILE
  (NAME = N'Ecr_audit',   FILENAME = N'<path>\Ecr_audit.ndf',   SIZE = 4GB, FILEGROWTH = 2GB) TO FILEGROUP [AUDIT];
ALTER DATABASE [Ecr] ADD FILE
  (NAME = N'Ecr_idx',     FILENAME = N'<path>\Ecr_idx.ndf',     SIZE = 2GB, FILEGROWTH = 1GB) TO FILEGROUP [INDEXES];
GO
