<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Ecr.Expressions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecr.Domain\Ecr.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NCalcSync" />
  </ItemGroup>

</Project>
