// <auto-generated />
using System;
using Ecr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EcrDbContext))]
    [Migration("20260904131018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("TableInstanceSeq", "doc");

            modelBuilder.HasSequence("TableRowSeq", "doc");

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.CalculationBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnDefId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_CalcBind_Act");

                    b.Property<string>("MatchJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodologyId")
                        .HasColumnType("int");

                    b.Property<string>("OutputCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColumnDefId", "MethodologyId", "OutputCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_CalculationBinding");

                    b.ToTable("CalculationBinding", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.ColumnDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CascadeFromColumnId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("DataType")
                        .HasColumnType("tinyint");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeaderL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBusinessKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_BK");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Del");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Hid");

                    b.Property<bool>("IsIndexed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Ix");

                    b.Property<bool>("IsMonthColumn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Mon");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_RO");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Req");

                    b.Property<bool>("IsScopeField")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_ColumnDef_Sc");

                    b.Property<string>("LookupFilter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LookupRegistryDefId")
                        .HasColumnType("int");

                    b.Property<byte?>("MonthNumber")
                        .HasColumnType("tinyint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<byte?>("Precision")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Scale")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StyleId")
                        .HasColumnType("int");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("TableDefId", "Id")
                        .HasName("UQ_ColumnDef_ForFk");

                    b.HasIndex("TableDefId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ColumnDef");

                    b.ToTable("ColumnDef", "cfg", t =>
                        {
                            t.HasTrigger("TR_ColumnDef_Immutable");

                            t.HasCheckConstraint("CK_ColumnDef_Lookup", "DataType <> 5 OR LookupRegistryDefId IS NOT NULL");

                            t.HasCheckConstraint("CK_ColumnDef_Month", "IsMonthColumn = 0 OR MonthNumber BETWEEN 1 AND 12");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.FormulaDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColumnDefId")
                        .HasColumnType("int");

                    b.Property<byte>("Dialect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0", "DF_Formula_Dialect");

                    b.Property<int>("EvaluationOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF_Formula_Order");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCrossSheet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Formula_Cross");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Formula_Del");

                    b.Property<bool>("IsSnapshot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Formula_Snap");

                    b.Property<int?>("RowDefId")
                        .HasColumnType("int");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormulaDef", "cfg", t =>
                        {
                            t.HasTrigger("TR_FormulaDef_Immutable");

                            t.HasCheckConstraint("CK_Formula_Scope", "(Scope = 0 AND ColumnDefId IS NOT NULL) OR (Scope = 1 AND RowDefId IS NOT NULL) OR (Scope = 2 AND ColumnDefId IS NOT NULL AND RowDefId IS NOT NULL)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.FormulaDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BindingId")
                        .HasColumnType("int");

                    b.Property<int?>("ColumnDefId")
                        .HasColumnType("int");

                    b.Property<byte>("DependsOnKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("FilterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormulaDefId")
                        .HasColumnType("int");

                    b.Property<short?>("PeriodOffset")
                        .HasColumnType("smallint");

                    b.Property<string>("RowKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<byte>("SourceKind")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableDefId", "RowKey", "ColumnDefId")
                        .HasDatabaseName("IX_FormulaDependency_Reverse");

                    b.ToTable("FormulaDependency", "cfg", t =>
                        {
                            t.HasCheckConstraint("CK_FDep_Source", "(SourceKind = 0 AND FormulaDefId IS NOT NULL) OR (SourceKind = 1 AND BindingId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.PeriodAccessRuleDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("FromSequence")
                        .HasColumnType("tinyint");

                    b.Property<byte>("OnOutOfWindow")
                        .HasColumnType("tinyint");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("SheetDefId")
                        .HasColumnType("int");

                    b.Property<int?>("TableDefId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("int");

                    b.Property<byte?>("ToSequence")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PeriodAccessRuleDef", "cfg", t =>
                        {
                            t.HasCheckConstraint("CK_PAR_Range", "FromSequence IS NULL OR ToSequence IS NULL OR FromSequence <= ToSequence");

                            t.HasCheckConstraint("CK_PAR_Target", "SheetDefId IS NOT NULL OR TableDefId IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RegistryDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DataRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF_RegDef_Rev");

                    b.Property<int>("DefinitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1, "DF_RegDef_Ver");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_RegDef_Act");

                    b.Property<bool>("IsTemporal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_RegDef_Temp");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SourceKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("2", "DF_RegDef_Src");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RegistryDef");

                    b.ToTable("RegistryDef", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RegistryFieldDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("DataType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_RegField_Key");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_RegField_Req");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int?>("RefRegistryDefId")
                        .HasColumnType("int");

                    b.Property<int>("RegistryDefId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistryDefId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RegistryFieldDef");

                    b.ToTable("RegistryFieldDef", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RowDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_RowDef_Del");

                    b.Property<bool>("IsReadOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_RowDef_RO");

                    b.Property<string>("LabelL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int?>("ParentRowDefId")
                        .HasColumnType("int");

                    b.Property<string>("RowKeyValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RowKey");

                    b.Property<byte>("RowKind")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StyleId")
                        .HasColumnType("int");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableDefId", "RowKeyValue")
                        .IsUnique()
                        .HasDatabaseName("UQ_RowDef");

                    b.ToTable("RowDef", "cfg", t =>
                        {
                            t.HasTrigger("TR_RowDef_Immutable");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.SheetDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_SheetDef_Del");

                    b.Property<bool>("IsMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_SheetDef_Mand");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_SheetDef_Vis");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("SheetGroup")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SheetDef");

                    b.ToTable("SheetDef", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.SheetGroupRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("RuleKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("SheetGroup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TargetGroup")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SheetGroupRule", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.StyleDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BackgroundArgb")
                        .HasColumnType("int");

                    b.Property<string>("BorderJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FontName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("FontSize")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<int?>("ForegroundArgb")
                        .HasColumnType("int");

                    b.Property<byte?>("HorizontalAlign")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsBold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Style_Bold");

                    b.Property<bool>("IsItalic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Style_Ital");

                    b.Property<string>("NumberFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("int");

                    b.Property<byte?>("VerticalAlign")
                        .HasColumnType("tinyint");

                    b.Property<bool>("WrapText")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Style_Wrap");

                    b.HasKey("Id");

                    b.HasIndex("TemplateVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_StyleDef");

                    b.ToTable("StyleDef", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TableDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("HeaderStyleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_TableDef_Del");

                    b.Property<byte>("LayoutKind")
                        .HasColumnType("tinyint");

                    b.Property<int?>("MaxDynamicRows")
                        .HasColumnType("int");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<byte>("RowMode")
                        .HasColumnType("tinyint");

                    b.Property<int>("SheetDefId")
                        .HasColumnType("int");

                    b.Property<byte>("StorageMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0", "DF_TableDef_Storage");

                    b.HasKey("Id");

                    b.HasIndex("SheetDefId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_TableDef");

                    b.ToTable("TableDef", "cfg", t =>
                        {
                            t.HasCheckConstraint("CK_TableDef_MaxRows", "RowMode = 0 OR MaxDynamicRows IS NULL OR MaxDynamicRows > 0");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TableRelationDef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Rel_Active");

                    b.Property<string>("MapJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("OnSourceChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0", "DF_Rel_OnChange");

                    b.Property<byte>("RelationKind")
                        .HasColumnType("tinyint");

                    b.Property<int>("SourceTableDefId")
                        .HasColumnType("int");

                    b.Property<int>("TargetTableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_TableRelationDef");

                    b.ToTable("TableRelationDef", "cfg", t =>
                        {
                            t.HasCheckConstraint("CK_Rel_NotSelf", "SourceTableDefId <> TargetTableDefId");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Template_Active");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Template_Code");

                    b.ToTable("Template", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClonedFromVersionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("PresentationRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF_TV_PresRev");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("SourceWorkbookHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("UQ_TemplateVersion");

                    b.ToTable("TemplateVersion", "cfg", t =>
                        {
                            t.HasCheckConstraint("CK_TV_Published", "Status <> 1 OR (PublishedAt IS NOT NULL AND PublishedByUserId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.ValidationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ColumnDefId")
                        .HasColumnType("int");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_VRule_Active");

                    b.Property<string>("MessageL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Severity")
                        .HasColumnType("tinyint");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableDefId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ValidationRule");

                    b.ToTable("ValidationRule", "cfg");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Dictionaries.RegistryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentEntryId")
                        .HasColumnType("bigint");

                    b.Property<int>("RegistryDefId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("RegistryEntries");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Dictionaries.RegistryEntryLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FromEntryId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistryRelationDefId")
                        .HasColumnType("int");

                    b.Property<long>("ToEntryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("RegistryEntryLinks");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Dictionaries.RegistryExternalKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RegistryEntryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistryExternalKeys");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Dictionaries.RegistryValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("RegistryEntryId")
                        .HasColumnType("bigint");

                    b.Property<int>("RegistryFieldDefId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<long?>("ValueRegistryEntryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistryValues");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.CellValue", b =>
                {
                    b.Property<int>("PeriodKeyValue")
                        .HasColumnType("int")
                        .HasColumnName("PeriodKey");

                    b.Property<long>("TableRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("TableRowId");

                    b.Property<int>("ColumnDefId")
                        .HasColumnType("int")
                        .HasColumnName("ColumnDefId");

                    b.Property<bool>("IsCalculated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_CellValue_Calc");

                    b.Property<bool>("IsEmpty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_CellValue_Empty");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int")
                        .HasColumnName("TableDefId");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int?>("ValueRegistryEntryId")
                        .HasColumnType("int");

                    b.Property<string>("ValueString")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ValueUnitId")
                        .HasColumnType("int");

                    b.HasKey("PeriodKeyValue", "TableRowId", "ColumnDefId");

                    b.ToTable("CellValue", "doc", t =>
                        {
                            t.HasCheckConstraint("CK_CellValue_Empty", "IsEmpty = 0 OR (ValueString IS NULL AND ValueNumeric IS NULL AND ValueDate IS NULL AND ValueBool IS NULL AND ValueRegistryEntryId IS NULL AND ValueUnitId IS NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NameL10n")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Document");

                    b.ToTable("Document", "doc");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.DocumentSheet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_DocSheet_Inc");

                    b.Property<int>("SheetDefId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "SheetDefId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DocumentSheet");

                    b.ToTable("DocumentSheet", "doc");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Period", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComputedCloseAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ComputedGraceAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ComputedOpenAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<int>("PeriodKeyValue")
                        .HasColumnType("int")
                        .HasColumnName("PeriodKey");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("ReopenedUntil")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Sequence")
                        .HasColumnType("tinyint");

                    b.Property<byte>("State")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "PeriodKeyValue")
                        .IsUnique()
                        .HasDatabaseName("UQ_Period");

                    b.ToTable("Period", "doc", t =>
                        {
                            t.HasCheckConstraint("CK_Period_Range", "PeriodStart <= PeriodEnd");

                            t.HasCheckConstraint("CK_Period_Seq", "Sequence BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.PeriodPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("GraceOffsetDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15, "DF_PP_Grace");

                    b.Property<int>("HardCloseOffsetDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(45, "DF_PP_Hard");

                    b.Property<int>("OpenOffsetDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF_PP_Open");

                    b.Property<int>("YearGraceOffsetDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(45, "DF_PP_Year");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_PeriodPolicy");

                    b.ToTable("PeriodPolicy", "doc", t =>
                        {
                            t.HasCheckConstraint("CK_PP_Order", "GraceOffsetDays <= HardCloseOffsetDays");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CurrentPeriodChangedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CurrentPeriodChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentPeriodId")
                        .HasColumnType("int");

                    b.Property<byte>("CurrentPeriodMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("0", "DF_Project_CPMode");

                    b.Property<string>("CurrentPeriodPinnedReason")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ExternalSettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchiving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Project_Arch");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<byte>("PeriodKind")
                        .HasColumnType("tinyint");

                    b.Property<int>("PeriodPolicyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TemplateVersionId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Central Asia Standard Time", "DF_Project_Tz");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.Property<int>("YearGraceOffsetDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(45, "DF_Project_YearGrace");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Project_Code");

                    b.ToTable("Project", "doc", t =>
                        {
                            t.HasCheckConstraint("CK_Project_Period", "PeriodStart <= PeriodEnd");

                            t.HasCheckConstraint("CK_Project_Pinned", "CurrentPeriodMode <> 1 OR (CurrentPeriodId IS NOT NULL AND CurrentPeriodPinnedReason IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.TableInstance", b =>
                {
                    b.Property<int>("PeriodKeyValue")
                        .HasColumnType("int")
                        .HasColumnName("PeriodKey");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TableDefId")
                        .HasColumnType("int");

                    b.HasKey("PeriodKeyValue", "Id");

                    b.HasIndex("PeriodKeyValue", "DocumentId", "TableDefId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TableInstance");

                    b.ToTable("TableInstance", "doc");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.TableRow", b =>
                {
                    b.Property<int>("PeriodKeyValue")
                        .HasColumnType("int")
                        .HasColumnName("PeriodKey");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_TableRow_Del");

                    b.Property<bool>("IsOrphaned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_TableRow_Orph");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("RowDefId")
                        .HasColumnType("int");

                    b.Property<string>("RowKeyValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RowKey");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("TableInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("PeriodKeyValue", "Id");

                    b.HasIndex("PeriodKeyValue", "TableInstanceId", "RowKeyValue")
                        .IsUnique()
                        .HasDatabaseName("UQ_TableRow_Key");

                    b.ToTable("TableRow", "doc");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.PasswordPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("ExpirationDays")
                        .HasColumnType("int");

                    b.Property<int>("LockoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(15, "DF_PwdP_Lck");

                    b.Property<int>("MaxFailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5, "DF_PwdP_Att");

                    b.Property<int>("MinLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12, "DF_PwdP_Len");

                    b.Property<bool>("RequireDigit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_PwdP_Dig");

                    b.Property<bool>("RequireSpecial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_PwdP_Spc");

                    b.Property<bool>("RequireUpper")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_PwdP_Up");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_PasswordPolicy");

                    b.ToTable("PasswordPolicy", "sec");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Code");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Group");

                    b.Property<bool>("IsDangerous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Perm_Dang");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission", "sec");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.ResourceGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Grant_Deny");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<byte>("ResourceKind")
                        .HasColumnType("tinyint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ResourceKind", "ResourceId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ResourceGrant");

                    b.ToTable("ResourceGrant", "sec");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Role_Act");

                    b.Property<bool>("IsBuiltIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Role_Built");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Role");

                    b.ToTable("Role", "sec");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PrincipalSid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("ScopeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0, "DF_User_Failed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_User_Active");

                    b.Property<bool>("IsBootstrapAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_User_Bootstrap");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_User_MustChg");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("PasswordPolicyId")
                        .HasColumnType("int");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WindowsSid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsBootstrapAdmin")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Bootstrap")
                        .HasFilter("[IsBootstrapAdmin] = 1");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_User_Name");

                    b.HasIndex("WindowsSid")
                        .IsUnique()
                        .HasDatabaseName("UX_User_Sid")
                        .HasFilter("[WindowsSid] IS NOT NULL");

                    b.ToTable("User", "sec", t =>
                        {
                            t.HasCheckConstraint("CK_User_Provider", "(Provider = 0 AND WindowsSid IS NOT NULL AND PasswordHash IS NULL) OR (Provider = 1 AND PasswordHash IS NOT NULL AND WindowsSid IS NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Units.Dimension", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BaseUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte?>("DenominatorDimensionId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDerived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Dim_Derived");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("NumeratorDimensionId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Dimension_Code");

                    b.ToTable("Dimension", "uom", t =>
                        {
                            t.HasCheckConstraint("CK_Dim_Derived", "IsDerived = 0 OR (NumeratorDimensionId IS NOT NULL AND DenominatorDimensionId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("DenominatorUnitId")
                        .HasColumnType("int");

                    b.Property<byte>("DimensionId")
                        .HasColumnType("tinyint");

                    b.Property<string>("DisplayFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("FactorToBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)")
                        .HasDefaultValue(1m, "DF_Unit_Factor");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_Unit_Active");

                    b.Property<bool>("IsBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false, "DF_Unit_Base");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeratorUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("OffsetToBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)")
                        .HasDefaultValue(0m, "DF_Unit_Offset");

                    b.Property<string>("SymbolL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Unit_Code");

                    b.HasIndex("DimensionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Unit_BasePerDimension")
                        .HasFilter("[IsBase] = 1");

                    b.ToTable("Unit", "uom", t =>
                        {
                            t.HasCheckConstraint("CK_Unit_Base", "IsBase = 0 OR (FactorToBase = 1 AND OffsetToBase = 0)");

                            t.HasCheckConstraint("CK_Unit_Factor", "FactorToBase <> 0");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Units.UnitConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Factor")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<int>("FromUnitId")
                        .HasColumnType("int");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Note")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<decimal>("Offset")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)")
                        .HasDefaultValue(0m, "DF_Conv_Offset");

                    b.Property<int>("ToUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromUnitId", "ToUnitId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Conversion");

                    b.ToTable("Conversion", "uom", t =>
                        {
                            t.HasCheckConstraint("CK_Conv_NotSelf", "FromUnitId <> ToUnitId");

                            t.HasCheckConstraint("CK_Conv_Note", "Kind <> 1 OR Note IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Workflow.ApprovalRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameL10n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalRoutes");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Workflow.ApprovalState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStepId")
                        .HasColumnType("int");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("PeriodKey")
                        .HasColumnType("int");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReopenReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReopenedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ReopenedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SheetDefId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "SheetDefId", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_ApprovalState");

                    b.ToTable("ApprovalState", "wf", t =>
                        {
                            t.HasCheckConstraint("CK_ApprState_Reopen", "ReopenedAt IS NULL OR ReopenReason IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Workflow.ApprovalStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRouteId")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApprovalSteps");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.ColumnDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.TableDef", null)
                        .WithMany("Columns")
                        .HasForeignKey("TableDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ColumnDef_Table");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.FormulaDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.TableDef", null)
                        .WithMany()
                        .HasForeignKey("TableDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Formula_Table");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.FormulaDependency", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.FormulaDef", null)
                        .WithMany()
                        .HasForeignKey("FormulaDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FDep_Formula");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RegistryFieldDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.RegistryDef", null)
                        .WithMany("Fields")
                        .HasForeignKey("RegistryDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RegField_Registry");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RowDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.TableDef", null)
                        .WithMany("Rows")
                        .HasForeignKey("TableDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RowDef_Table");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.SheetDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.TemplateVersion", null)
                        .WithMany("Sheets")
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SheetDef_Version");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TableDef", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.SheetDef", null)
                        .WithMany("Tables")
                        .HasForeignKey("SheetDefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TableDef_Sheet");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TemplateVersion", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Configuration.Template", null)
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TemplateVersion_Template");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.CellValue", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Documents.TableRow", null)
                        .WithMany()
                        .HasForeignKey("PeriodKeyValue", "TableRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CellValue_Row");

                    b.HasOne("Ecr.Domain.Entities.Configuration.ColumnDef", null)
                        .WithMany()
                        .HasForeignKey("TableDefId", "ColumnDefId")
                        .HasPrincipalKey("TableDefId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CellValue_Column");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Document", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Documents.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Document_Project");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.DocumentSheet", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Documents.Document", null)
                        .WithMany("Sheets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DocSheet_Document");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Period", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Documents.Project", null)
                        .WithMany("Periods")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Period_Project");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.TableRow", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Documents.TableInstance", null)
                        .WithMany()
                        .HasForeignKey("PeriodKeyValue", "TableInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TableRow_Instance");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Security.ResourceGrant", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Grant_Role");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Units.Unit", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Units.Dimension", null)
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Unit_Dimension");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Workflow.ApprovalStep", b =>
                {
                    b.HasOne("Ecr.Domain.Entities.Workflow.ApprovalRoute", null)
                        .WithMany("Steps")
                        .HasForeignKey("ApprovalRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.RegistryDef", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.SheetDef", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TableDef", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.Template", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Configuration.TemplateVersion", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Document", b =>
                {
                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Documents.Project", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("Ecr.Domain.Entities.Workflow.ApprovalRoute", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
